--liquibase formatted sql

--changeset dell:1596641125646-1
CREATE TABLE cours (id_cours INT DEFAULT NULL NULL, nom VARCHAR(30) NULL, prenomProf VARCHAR(30) NULL, moyenneHeure DECIMAL(7) DEFAULT NULL NULL, domicile VARCHAR(30) NULL);

--changeset dell:1596641125646-2
CREATE TABLE etudiant (id_etudiant INT DEFAULT NULL NULL, nom VARCHAR(30) NULL, prenom VARCHAR(30) NULL, moyenne DECIMAL(7) DEFAULT NULL NULL, domicile VARCHAR(30) NULL);

--changeset dell:1596641125646-3
CREATE TABLE professeur (id INT UNSIGNED AUTO_INCREMENT NOT NULL, Prenom VARCHAR(30) NOT NULL, Nom VARCHAR(30) NOT NULL, Mail VARCHAR(50) NOT NULL, CONSTRAINT PK_PROFESSEUR PRIMARY KEY (id));

--changeset dell:1596641125646-4
CREATE TABLE students (student_id INT AUTO_INCREMENT NOT NULL, student_name VARCHAR(100) NOT NULL, email_address VARCHAR(100) NOT NULL, contact VARCHAR(30) NOT NULL, gender VARCHAR(15) NOT NULL, country VARCHAR(50) NOT NULL, datetime datetime DEFAULT NOW() NOT NULL, Inscription timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id));

